id = "io.buildpacks.stacks.jammy"
homepage = "https://github.com/paketo-buildpacks/jammy-full-stack"
maintainer = "Paketo Buildpacks"

platforms = ["linux/amd64", "linux/arm64"]

[build]
  description = "ubuntu:jammy with compilers and common libraries and utilities"
  dockerfile = "./build.Dockerfile"
  gid = 1000
  shell = "/bin/bash"
  uid = 1001

  [build.args]
    architecture = "amd64"

    sources = """
    deb http://archive.ubuntu.com/ubuntu jammy main universe multiverse
    deb http://archive.ubuntu.com/ubuntu jammy-updates main universe multiverse
    deb http://archive.ubuntu.com/ubuntu jammy-security main universe multiverse
    """

    packages = """\
    autoconf \
    automake \
    bison \
    build-essential \
    bzr \
    ca-certificates \
    cmake \
    comerr-dev \
    curl \
    dh-python \
    dnsutils \
    file \
    flex \
    gdb \
    gir1.2-gdkpixbuf-2.0 \
    gir1.2-rsvg-2.0 \
    git \
    gnupg \
    gnupg1 \
    gnupg1-curl \
    graphviz \
    gsfonts \
    gss-ntlmssp \
    gss-ntlmssp-dev \
    imagemagick \
    imagemagick-6-common \
    jq \
    krb5-user \
    libaio-dev \
    libaio1 \
    libarchive-extract-perl \
    libargon2-0 \
    libargon2-0-dev \
    libatm1 \
    libatm1-dev \
    libaudiofile-dev \
    libaudiofile1 \
    libavcodec-dev \
    libavcodec58 \
    libbabeltrace1 \
    libblas-dev \
    libblas3 \
    libc6 \
    libcurl4 \
    libcurl4-openssl-dev \
    libdjvulibre-text \
    libdjvulibre21 \
    libdw1 \
    liberror-perl \
    libestr-dev \
    libestr0 \
    libexif12 \
    libffi-dev \
    libffi8 \
    libfl-dev \
    libfl2 \
    libfribidi-dev \
    libfribidi0 \
    libgcrypt20 \
    libgcrypt20-dev \
    libgd-dev \
    libgmp-dev \
    libgmp10 \
    libgmpxx4ldbl \
    libgnutls-openssl27 \
    libgnutls28-dev \
    libgnutls30 \
    libgnutlsxx28 \
    libgraphviz-dev \
    libharfbuzz-icu0 \
    libicu-dev \
    libidn12 \
    libidn11-dev \
    libilmbase25 \
    libjson-glib-1.0-0 \
    libjson-glib-dev \
    libkrb5-dev \
    liblapack-dev \
    liblapack3 \
    libldap-2.5-0 \
    libldap2-dev \
    liblockfile-bin \
    liblockfile-dev \
    liblockfile1 \
    libmagic-dev \
    libmagic1 \
    libmagickwand-dev \
    libmariadb-dev-compat \
    libmariadb3 \
    libmodule-pluggable-perl \
    libncurses5 \
    libncurses5-dev \
    libnih-dbus-dev \
    libnih-dbus1 \
    libnl-3-200 \
    libnl-3-dev \
    libnl-genl-3-200 \
    libnl-genl-3-dev \
    libopenblas-base \
    libopenblas-dev \
    libopenexr25 \
    liborc-0.4-0 \
    liborc-0.4-dev \
    libp11-kit-dev \
    libp11-kit0 \
    libpam-cap \
    libpango1.0-0 \
    libpango1.0-dev \
    libpathplan4 \
    libpcre32-3 \
    libpq-dev \
    libpq5 \
    libproxy-dev \
    libproxy1v5 \
    libpython3.10-stdlib \
    libpython3.10 \
    libreadline-dev \
    libreadline8 \
    librtmp-dev \
    libsasl2-2 \
    libsasl2-dev \
    libsasl2-modules \
    libsasl2-modules-gssapi-mit \
    libselinux1 \
    libselinux1-dev \
    libsigc++-2.0-0v5 \
    libsigc++-2.0-dev \
    libsigsegv2 \
    libsodium23 \
    libsodium-dev \
    libsqlite0 \
    libsqlite0-dev \
    libsqlite3-0 \
    libsqlite3-dev \
    libssl-dev \
    libsysfs-dev \
    libsysfs2 \
    libtasn1-6 \
    libtasn1-6-dev \
    libterm-ui-perl \
    libtiffxx5 \
    libtirpc-dev \
    libtirpc-common \
    libtool \
    libunwind8-dev \
    libunwind8 \
    libustr-1.0-1 \
    libustr-dev \
    libwmf0.2-7 \
    libwrap0-dev \
    libwrap0 \
    libxapian-dev \
    libxapian30 \
    libxdot4 \
    libxslt1-dev \
    libxslt1.1 \
    libyaml-0-2 \
    libyaml-dev \
    lockfile-progs \
    lsof \
    lzma \
    mercurial \
    net-tools \
    ocaml-base-nox \
    openssh-client \
    openssl \
    psmisc \
    python3 \
    rsync \
    subversion \
    sysstat \
    tzdata \
    ubuntu-minimal \
    unixodbc \
    unixodbc-dev \
    unzip \
    uuid \
    uuid-dev \
    wget \
    zip \
    """

  [build.platforms."linux/arm64".args]
    architecture = "arm64"

    sources = """
    deb http://ports.ubuntu.com/ubuntu-ports/ jammy main universe multiverse
    deb http://ports.ubuntu.com/ubuntu-ports/ jammy-updates main universe multiverse
    deb http://ports.ubuntu.com/ubuntu-ports/ jammy-security main universe multiverse
    """

[run]
  description = "ubuntu:jammy with common libraries and utilities"
  dockerfile = "./run.Dockerfile"
  gid = 1000
  shell = "/bin/bash"
  uid = 1002

  [run.args]
    architecture = "amd64"

    sources = """
    deb http://archive.ubuntu.com/ubuntu jammy main universe multiverse
    deb http://archive.ubuntu.com/ubuntu jammy-updates main universe multiverse
    deb http://archive.ubuntu.com/ubuntu jammy-security main universe multiverse
    """

    packages = """\
    ca-certificates \
    curl \
    dh-python \
    dnsutils \
    file \
    gir1.2-gdkpixbuf-2.0 \
    gir1.2-rsvg-2.0 \
    gnupg \
    gnupg1 \
    graphviz \
    gsfonts \
    gss-ntlmssp \
    imagemagick \
    imagemagick-6-common \
    jq \
    krb5-user \
    libaio1 \
    libarchive-extract-perl \
    libargon2-0 \
    libatm1 \
    libaudiofile1 \
    libavcodec58 \
    libbabeltrace1 \
    libblas3 \
    libc6 \
    libcurl4 \
    libdjvulibre-text \
    libdjvulibre21 \
    libdw1 \
    liberror-perl \
    libestr0 \
    libexif12 \
    libffi8 \
    libfl2 \
    libfribidi0 \
    libgcrypt20 \
    libgmp10 \
    libgmpxx4ldbl \
    libgnutls-openssl27 \
    libgnutls28-dev \
    libgnutls30 \
    libgnutlsxx28 \
    libgraphviz-dev \
    libharfbuzz-icu0 \
    libidn12 \
    libilmbase25 \
    libisl23 \
    libjson-glib-1.0-0 \
    libjsoncpp25 \
    liblapack3 \
    libldap-2.5-0 \
    liblockfile-bin \
    liblockfile1 \
    libmagic1 \
    libmariadb3 \
    libmodule-pluggable-perl \
    libmpc3 \
    libmpfr6 \
    libncurses5 \
    libnih-dbus1 \
    libnl-3-200 \
    libnl-genl-3-200 \
    libopenblas-base \
    libopenexr25 \
    liborc-0.4-0 \
    libp11-kit0 \
    libpam-cap \
    libpango1.0-0 \
    libpango1.0-dev \
    libpathplan4 \
    libpcre32-3 \
    libpq5 \
    libproxy1v5 \
    libpython3-stdlib \
    libpython3.10 \
    libreadline8 \
    librhash0 \
    libsasl2-2 \
    libsasl2-modules \
    libsasl2-modules-gssapi-mit \
    libselinux1 \
    libsigc++-2.0-0v5 \
    libsigsegv2 \
    libsodium23 \
    libsqlite0 \
    libsqlite3-0 \
    libsysfs2 \
    libtasn1-6 \
    libterm-ui-perl \
    libtiffxx5 \
    libtirpc-common \
    libunwind8 \
    libustr-1.0-1 \
    libuv1 \
    libwmf0.2-7 \
    libwrap0 \
    libxapian30 \
    libxdot4 \
    libxslt1.1 \
    libyaml-0-2 \
    lockfile-progs \
    lsof \
    lzma \
    net-tools \
    ocaml-base-nox \
    openssh-client \
    openssl \
    psmisc \
    python3 \
    rsync \
    subversion \
    tzdata \
    ubuntu-minimal \
    unixodbc \
    unzip \
    uuid \
    wget \
    zip \
    """

  [run.platforms."linux/arm64".args]
    architecture = "arm64"

    sources = """
    deb http://ports.ubuntu.com/ubuntu-ports/ jammy main universe multiverse
    deb http://ports.ubuntu.com/ubuntu-ports/ jammy-updates main universe multiverse
    deb http://ports.ubuntu.com/ubuntu-ports/ jammy-security main universe multiverse
    """